<?php title('Lost Password','index');

	$l_passsubj = 'Password change for the SnarkPit';
	$l_from = "From: leperous@snarkpit.net\r\n"."Reply-To: leperous@snarkpit.net\r\n"."X-Mailer: PHP4";

if($actkey=$_GET['actkey']) {
	$sql = mysql_query("SELECT user_id FROM users WHERE user_actkey = '$actkey' LIMIT 1");
	if(!$row = mysql_fetch_array($sql)) error_die('Wrong activation code!');
	$update_id = $row['user_id'];

	@mysql_query("UPDATE users SET password = user_newpasswd, user_actkey = '', user_newpasswd = '' WHERE user_id = '$update_id' LIMIT 1");

	echo 'Your password has been changed. <a href="'.$url_login.'">Click here</a> to login.';
	footer();
}

if($submit) {
	if(!$user OR !$email) $error = 'Please enter a username/e-mail address';
	$user = addslashes($user);
	$sql = mysql_query("SELECT user_email FROM users_profile WHERE username = '$user' LIMIT 1");
	$checkinfo = mysql_fetch_array($sql);
	if($checkinfo['user_email']!=$email) $error = 'Wrong e-mail address';

	if(!$error) {

	$sql = mysql_query("SELECT user_id, activated FROM users WHERE username = '$user' LIMIT 1");
	$arow = mysql_fetch_array($sql);
	if($arow['activated']!=1) {
		$sql = mysql_query("SELECT actkey FROM register WHERE userid = '$arow[user_id]' LIMIT 1");
		if(!$actarray = mysql_fetch_array($sql)) error_die("There has been a screwup somewhere, please contact the site admin!");
		$message = "Please activate your account by visiting http://www.snarkpit.net/?page=activate&key=".$actarray[actkey];
		mail($email, $l_passsubj, $message, $l_from);
		echo 'Your activation code has been re-sent to <b>'.$email;

	} else {

	$chars = array( 
		  "a","A","b","B","c","C","d","D","e","E","f","F","g","G","h","H","i","I","j","J",
		  "k","K","l","L","m","M","n","N","o","O","p","P","q","Q","r","R","s","S","t","T",
		  "u","U","v","V","w","W","x","X","y","Y","z","Z","1","2","3","4","5","6","7","8",
		  "9","0"
		  );

	$max_elements = count($chars) - 1;
	srand((double)microtime()*1000000);
	$newpw = $chars[rand(0,$max_elements)];
	$newpw .= $chars[rand(0,$max_elements)];
	$newpw .= $chars[rand(0,$max_elements)];  
	$newpw .= $chars[rand(0,$max_elements)]; 
	$newpw .= $chars[rand(0,$max_elements)]; 
	$newpw .= $chars[rand(0,$max_elements)]; 
	$newpw .= $chars[rand(0,$max_elements)]; 
	$newpw .= $chars[rand(0,$max_elements)];

	$newpw_enc = md5($newpw);
	$key = md5(md5($newpw_enc));
   
if($userdata['user_id']==1) { echo 'key:'.$key.'<br>pw:'.$newpw.'<p>'; }

	if(!$sql = mysql_query("UPDATE users SET user_actkey = '$key', user_newpasswd = '$newpw_enc' WHERE user_id = '$arow[user_id]'")) error_die("Problem setting new key, please try again.");
	$message = "You are receiving this email because you (or someone pretending to be you)
has requested a password change at the SnarkPit. If you believe you have
received this message in error simply delete it and your password will remain
the same.

Your new password as generated by the forums is: $newpw
In order for this change to take effect you must visit this page:

http://$SERVER_NAME".$_SERVER['PHP_SELF']."?page=sendpassword&actkey=$key

Once you have visited the page your password will be changed in our database,
and you may login to the profile section and change it as desired.

Regards,
-Leperous (leperous@snarkpit.net)
	";

	mail($email, $l_passsubj, $message, $l_from);
	echo 'Password sent- it will not come into effect until you visit the link e-mailed to you.';
} 
footer();
} } 


if($error) echo '<b><font color=red>Error:</font></b> '.$error.'</p>'; ?>
Please enter your username and password in the below
<FORM ACTION="?page=sendpassword&submit" METHOD="POST">
<TABLE BORDER="0" CELLPADDING="1" CELLSPACING="1" WIDTH="100%">
	<TR ALIGN="LEFT">
		<TD width=15%>Username:</TD>
		<TD width=85%><INPUT TYPE="TEXT" NAME="user" VALUE="<?=$userdata[username]?>" SIZE="32" maxlength="50" class=textinput></TD>
	</TR>
	<TR ALIGN="LEFT">
 		<TD>E-mail address:</TD>
		<TD><INPUT TYPE="TEXT" NAME="email" SIZE="32" value="<?php if($userdata) echo mysql_result(mysql_query("SELECT user_email FROM users_profile WHERE user_id = '$userdata[user_id]' LIMIT 1"),0); ?>" MAXLENGTH="100" class=textinput></TD>
	</TR>
	<TR>
		<td></td><TD><INPUT TYPE="SUBMIT" NAME="submit" VALUE="Send" class=submit></TD>
	</TR>
</TABLE></p>
If your e-mail address has changed and so you can't have it re-sent, or never received your activation e-mail, please <b><a href='?page=about'>e-mail us</a></b>.
